[project]
name = "torchpipe"
version = "0.1.28"

requires-python = ">=3.8"
description = "Serving inside Pytorch"
dependencies = [
    "torch",
    "omniback>=0.1.27",
    "setuptools<81",
    "packaging",
    "tqdm",
    "requests",
    "ninja",
    "cmake",
    "patchelf",
]

[tool.setuptools]
packages = ["torchpipe"]

[tool.setuptools.package-data]
torchpipe = ["lib/*.so"]
