[project]
name = "torchpipe"
version = "0.2.1"

requires-python = ">=3.8"
description = "Serving inside Pytorch"
dependencies = [
    "torch>=2.2",
    "omniback>=0.1.27",
    "setuptools",
    "packaging",
    "tqdm",
    "requests",
    "ninja",
    "cmake",
    "patchelf",
]

[tool.setuptools]
packages = ["torchpipe"]

[tool.setuptools.package-data]
torchpipe = ["lib/*.so"]