
batching_timeout = 5 #默认的凑batch的超时时间
instance_num = 2 
[jpg_decoder]
backend = "S[S[DecodeTensor,ResizeTensor,cvtColorTensor,SyncTensor],(or)S[DecodeMat,ResizeMat,CvtColorMat,Mat2Tensor,SyncTensor]]"

resize_h = 224
resize_w = 224

color = "rgb"
instance_num = 4

# Schedule'parameter
next = "resnet18"

[resnet18]
precision = "best" 

backend = "SyncTensor[TensorrtTensor]" 
instance_num = 2 
max = 4 
mean = "123.675, 116.28, 103.53" # 255*"0.485, 0.456, 0.406"
model = "../../test/assets/resnet18.onnx" 
std = "58.395, 57.120, 57.375" # 255*"0.229, 0.224, 0.225"
# TensorrtTensor
"model::cache" = "./resnet18.trt" # or ./resnet18.trt.encrypted
save_dir = "./cache_dir"
calibrate_input = "./cache_dir"
calibrate_cache = "./resnet18_int8.cache" # optinal
