# Schedule'parameter
batching_timeout = 1
instance_num = 1

[jpg_decoder]
backend = "Torch[ Sequential[DecodeTensor,ResizeTensor,CvtColorTensor] ]"
color = "rgb"
instance_num = 3
next = "cpu_decoder"
resize_h = 232
resize_w = 232

[cpu_decoder]
backend = "Torch[Sequential[DecodeMat,ResizeMat,CvtColorMat,Mat2Tensor]]"
color = "rgb"
filter = "or"
instance_num = 4
resize_h = 232
resize_w = 232
