# Schedule'parameter
batching_timeout = 1 
instance_num =1

[jpg_decoder]
backend = "Torch[ Sequential[DecodeTensor,ResizeTensor,CvtColorTensor] ]" 
resize_h = 232
resize_w = 232 
color = "rgb"
next = "cpu_decoder"
instance_num =3

[cpu_decoder]
backend = "Torch[Sequential[DecodeMat,ResizeMat,cvtColorMat,Mat2Tensor]]" 
filter = "or" 
resize_h = 232 
resize_w = 232 
color = "rgb"
instance_num =4


