batching_timeout = 5 #默认的凑batch的超时时间
precision="fp16"

[jpg_decoder]
backend = "Sequential[DecodeTensor,(result2other)cvtColorTensor,ResizePadTensor,SyncTensor]"
color = "bgr"
instance_num = 5
max_h = 640
max_w = 640

next = "detect"
[detect]
# 静态batch， max默认为1
backend = "S[TensorrtTensor,PostProcYoloV8,SyncTensor]" 
batching_timeout = 5 #默认的凑batch的超时时间
instance_num = 1 
max = 4 
std="255,255,255"
model = "./yolov8n.onnx" 
"model::cache" = "./yolov8n.trt" 
next = "remove_extra_key" 
net_h =640
net_w = 640

[remove_extra_key]
map = "detect[result:data]"
