
[preprocess]
'backend' = 'S[DecodeMat,CvtColorMat,ResizeMat,Mat2Tensor,SyncTensor]'
'color' = 'rgb'
instance_num = 2
next = 'visual_encoder'
'resize_h' = '384'
'resize_w' = '384'

[visual_encoder]
# PluginCacher is used to cache parameters and input data for (tensorrt) plugin
'backend' = 'SyncTensor[TensorrtTensor]'

# cal_request_size_method = "CalTorchBatchSize" # calc. request_size according to torch tensor size
instance_num = 2
max = '1x3x384x384'
'mean' = '127.5,127.5,127.5'
'model' = '/workspace/VILA/onnx/visual_encoder.onnx'
'model::cache' = './visual_encoder.trt'

'std' = '127.5,127.5,127.5'

# use InsertTensor
